# Generated by Django 3.2.8 on 2021-10-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='user',
            new_name='owner',
        ),
    ]
